from __future__ import annotations

import uuid
from typing import Any

from pydantic import BaseModel, Field


class RetrievalFilters(BaseModel):
    document_type: str | None = None
    category: str | None = None
    subcategory: str | None = None
    academic_year: str | None = None
    term: str | None = None
    original_language: str | None = None

    def compact(self) -> dict[str, str]:
        return {key: value for key, value in self.model_dump().items() if value}


class ChatRequest(BaseModel):
    message: str = Field(min_length=1, max_length=4000)
    # A fresh thread per request when the client omits it, so an omitted id can NEVER share one
    # global in-memory LangGraph thread (cross-session memory bleed). The frontend always sends its
    # own per-chat id, so this only hardens the omitted-id case.
    conversation_id: str = Field(default_factory=lambda: uuid.uuid4().hex, min_length=1, max_length=128)
    db_conversation_id: uuid.UUID | None = None
    filters: RetrievalFilters | None = None
    backend_personalization_context: str | None = Field(
        default=None,
        max_length=6000,
        exclude=True,
        repr=False,
    )


class Citation(BaseModel):
    source_url: str
    title: str
    section: str | None = None
    page_number: int | None = None
    excerpt: str
    score: float | None = None


class ChatResponse(BaseModel):
    answer: str
    citations: list[Citation] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0)
    tool_trace: list[dict[str, Any]] = Field(default_factory=list)
    needs_human_review: bool = False
    db_conversation_id: uuid.UUID | None = None
    # Short, content-derived next questions shown under the answer (backend-generated by a small/fast
    # model). Empty → the frontend falls back to its rule-based chips. Kept brief and few by design.
    suggested_follow_ups: list[str] = Field(default_factory=list)


class IngestRunRequest(BaseModel):
    urls: list[str] | None = None
    force: bool = False


class IngestRunResponse(BaseModel):
    crawled_documents: int
    indexed_chunks: int
    skipped_documents: int = 0
    sources: list[str] = Field(default_factory=list)
