-- Add stable bilingual course names for UI/chat localization.

alter table courses add column if not exists course_title_vi text;
alter table courses add column if not exists name_vi text;

with course_name_vi(course_code, title_vi) as (
    values
        ('GEN101', 'Tiếng Anh học thuật'),
        ('GEN102', 'Tư duy phản biện'),
        ('GEN103', 'Đạo đức và tham gia công dân'),
        ('GEN104', 'Viết khoa học'),
        ('GEN105', 'Tư duy định lượng'),
        ('GEN106', 'Nghiên cứu toàn cầu'),
        ('VIE101', 'Văn hóa và xã hội Việt Nam'),
        ('DAT101', 'Nhập môn dữ liệu'),
        ('ICT101', 'Công cụ số cho học tập đại học'),
        ('PE101', 'Giáo dục thể chất'),
        ('SKL101', 'Sẵn sàng nghề nghiệp'),
        ('BUS101', 'Nguyên lý quản trị'),
        ('BUS120', 'Kế toán tài chính'),
        ('BUS130', 'Thống kê kinh doanh'),
        ('ECON101', 'Kinh tế vi mô'),
        ('LAW210', 'Luật kinh doanh'),
        ('BUS201', 'Quản trị marketing'),
        ('BUS220', 'Tài chính doanh nghiệp'),
        ('BUS230', 'Phân tích kinh doanh'),
        ('BUS250', 'Hành vi tổ chức'),
        ('BUS260', 'Quản trị vận hành'),
        ('BUS310', 'Khởi nghiệp'),
        ('BUS320', 'Quản trị chiến lược'),
        ('BUS330', 'Hành vi người tiêu dùng'),
        ('BUS340', 'Phân tích chuỗi cung ứng'),
        ('BUS410', 'Kinh doanh quốc tế'),
        ('BUS420', 'Phân tích đầu tư'),
        ('BUS430', 'Đổi mới dịch vụ'),
        ('INT400', 'Thực tập nghề nghiệp'),
        ('CAP401', 'Đồ án tốt nghiệp kinh doanh'),
        ('CSC101', 'Cơ sở lập trình'),
        ('CSC102', 'Lập trình hướng đối tượng'),
        ('MAT101', 'Giải tích I'),
        ('MAT102', 'Đại số tuyến tính'),
        ('PHY101', 'Vật lý cho kỹ sư'),
        ('LAB100', 'An toàn phòng thí nghiệm kỹ thuật'),
        ('CSC202', 'Cấu trúc dữ liệu và thuật toán'),
        ('CSC250', 'Hệ cơ sở dữ liệu'),
        ('ECE210', 'Hệ thống số'),
        ('CSC260', 'Mạng máy tính'),
        ('CSC301', 'Hệ điều hành'),
        ('CSC310', 'Trí tuệ nhân tạo'),
        ('CSC330', 'Kỹ thuật phần mềm'),
        ('CSC340', 'Kiến trúc máy tính'),
        ('CSC350', 'Tương tác người-máy'),
        ('CSC360', 'Cơ sở an ninh mạng'),
        ('CSC401', 'Hệ thống học máy'),
        ('CSC420', 'Điện toán đám mây'),
        ('CSC430', 'Kỹ thuật dữ liệu'),
        ('CSC440', 'Thị giác máy tính'),
        ('CSC490', 'Đồ án tốt nghiệp khoa học máy tính'),
        ('HSC101', 'Nền tảng khoa học y sinh'),
        ('BIO110', 'Sinh học người'),
        ('CHEM101', 'Hóa học đại cương'),
        ('HSC120', 'Nhập môn hệ thống y tế'),
        ('LAB101', 'An toàn phòng thí nghiệm lâm sàng'),
        ('MED210', 'Giải phẫu người'),
        ('NUR220', 'Giao tiếp trong y tế'),
        ('HSC230', 'Dịch tễ học'),
        ('HSC240', 'Thống kê sinh học'),
        ('HSC250', 'Tâm lý học sức khỏe'),
        ('HSC310', 'Kỹ năng lâm sàng'),
        ('HSC320', 'Sinh lý bệnh'),
        ('HSC330', 'Chất lượng chăm sóc sức khỏe'),
        ('HSC340', 'Thực hành sức khỏe cộng đồng'),
        ('HSC410', 'Thực hành dựa trên bằng chứng'),
        ('HSC420', 'Chính sách y tế'),
        ('HSC430', 'Phương pháp nghiên cứu lâm sàng'),
        ('HSC440', 'An toàn người bệnh'),
        ('CLN490', 'Đồ án tốt nghiệp lâm sàng'),
        ('LIB101', 'Seminar nghệ thuật tự do'),
        ('ENG120', 'Viết học thuật'),
        ('PSY101', 'Nhập môn tâm lý học'),
        ('SOC110', 'Khảo cứu xã hội'),
        ('COM201', 'Truyền thông và xã hội'),
        ('EDU220', 'Khoa học học tập'),
        ('ART230', 'Truyền thông thị giác'),
        ('VIE210', 'Nghiên cứu văn hóa Việt Nam'),
        ('PSY250', 'Phương pháp nghiên cứu tâm lý học'),
        ('COM260', 'Kể chuyện số'),
        ('SOC310', 'Xã hội đô thị'),
        ('RES300', 'Seminar nghiên cứu bậc cử nhân'),
        ('EDU320', 'Thiết kế đánh giá và học tập'),
        ('ART330', 'Xưởng thiết kế'),
        ('STA210', 'Thống kê ứng dụng'),
        ('CAP410', 'Đồ án tốt nghiệp nghệ thuật tự do')
)
update courses c
set
    course_title_vi = course_name_vi.title_vi,
    name_vi = course_name_vi.title_vi
from course_name_vi
where coalesce(c.code, c.course_code) = course_name_vi.course_code;
