// Realistic demo data for the VinUni Student Copilot portal. This is the FALLBACK layer:
// api.ts uses real FastAPI endpoints where they exist (chat, sources, ingest) and falls
// back to these fixtures for the portal screens the Python backend does not yet serve.
//
// Everything here is plausible-but-fake. Replace each consumer in api.ts with a real
// fetch() once the matching endpoint ships — the shapes already match portalTypes.ts.

import type {
  AdminStats,
  AnalyticsOverview,
  CalendarEvent,
  ClassSession,
  Deadline,
  KnowledgeSource,
  Notification,
  StudentProfile,
  SuggestedQuestion,
  SupportTicket,
  TuitionStatus,
  UnansweredQuestion,
} from "./portalTypes";

// Anchored "now" for deterministic relative dates in the demo (matches PRD timeframe).
// Using a fixed base keeps "days left" badges stable across renders/builds.
const NOW = new Date("2026-06-18T08:00:00+07:00");

function daysFromNow(days: number, hour = 23, minute = 59): string {
  const d = new Date(NOW);
  d.setDate(d.getDate() + days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

export const MOCK_PROFILE: StudentProfile = {
  student_id: "V2024001",
  full_name: "Nguyễn Minh Anh",
  preferred_name: "Minh Anh",
  program: "BS Computer Science",
  college: "College of Engineering & Computer Science",
  year: 2,
  intake: "Fall 2024",
  email: "minh.anh.nguyen@vinuni.edu.vn",
  advisor: "Dr. Trần Quốc Bảo",
  gpa: 3.62,
  credits_earned: 48,
  credits_required: 120,
};

export const MOCK_SCHEDULE: ClassSession[] = [
  {
    id: "cs-301",
    course_code: "COMP3010",
    course_title: "Algorithms & Data Structures",
    day: "Thu",
    start: "09:00",
    end: "10:30",
    room: "G-201",
    building: "Gallery Building",
    instructor: "Dr. Lê Thị Hương",
  },
  {
    id: "cs-302",
    course_code: "COMP3025",
    course_title: "Database Systems",
    day: "Thu",
    start: "11:00",
    end: "12:30",
    room: "G-114",
    building: "Gallery Building",
    instructor: "Dr. Phạm Văn Đức",
  },
  {
    id: "cs-303",
    course_code: "MATH2040",
    course_title: "Probability & Statistics",
    day: "Thu",
    start: "14:00",
    end: "15:30",
    room: "C-305",
    building: "Cohort Building",
    instructor: "Dr. Nguyễn Hải Yến",
  },
  {
    id: "cs-304",
    course_code: "COMP3010",
    course_title: "Algorithms & Data Structures (Lab)",
    day: "Fri",
    start: "09:00",
    end: "11:00",
    room: "Lab-2",
    building: "Gallery Building",
    instructor: "TA Đỗ Anh Khoa",
  },
  {
    id: "cs-305",
    course_code: "WRIT2010",
    course_title: "Technical Writing",
    day: "Fri",
    start: "13:00",
    end: "14:30",
    room: "C-210",
    building: "Cohort Building",
    instructor: "Dr. Sarah Mitchell",
  },
];

export const MOCK_DEADLINES: Deadline[] = [
  {
    id: "d1",
    title: "Problem Set 6 — Dynamic Programming",
    course_code: "COMP3010",
    kind: "assignment",
    due_at: daysFromNow(2),
    source_title: "COMP3010 Syllabus (Spring 2026)",
    source_url: "https://vinuni.edu.vn/academics/comp3010-syllabus",
  },
  {
    id: "d2",
    title: "Course Drop deadline (no W on transcript)",
    kind: "registration",
    due_at: daysFromNow(4),
    source_title: "Academic Calendar 2025–2026",
    source_url: "https://vinuni.edu.vn/academic-calendar",
  },
  {
    id: "d3",
    title: "Database Systems — Midterm Project",
    course_code: "COMP3025",
    kind: "exam",
    due_at: daysFromNow(6),
    source_title: "COMP3025 Syllabus (Spring 2026)",
    source_url: "https://vinuni.edu.vn/academics/comp3025-syllabus",
  },
  {
    id: "d4",
    title: "Tuition installment 2 due",
    kind: "tuition",
    due_at: daysFromNow(12),
    source_title: "Student Financial Services — Payment Schedule",
    source_url: "https://vinuni.edu.vn/tuition-payment-schedule",
  },
  {
    id: "d5",
    title: "Technical Writing — Draft submission",
    course_code: "WRIT2010",
    kind: "assignment",
    due_at: daysFromNow(9),
  },
];

export const MOCK_TUITION: TuitionStatus = {
  currency: "VND",
  total_charged_vnd: 320_000_000,
  total_paid_vnd: 240_000_000,
  balance_vnd: 80_000_000,
  next_due_at: daysFromNow(12),
  next_due_amount_vnd: 40_000_000,
  items: [
    {
      id: "t1",
      label: "Spring 2026 — Installment 1",
      term: "Spring 2026",
      amount_vnd: 160_000_000,
      status: "paid",
      paid_at: daysFromNow(-40),
    },
    {
      id: "t2",
      label: "Spring 2026 — Installment 2",
      term: "Spring 2026",
      amount_vnd: 40_000_000,
      status: "due",
      due_at: daysFromNow(12),
    },
    {
      id: "t3",
      label: "Spring 2026 — Installment 3",
      term: "Spring 2026",
      amount_vnd: 40_000_000,
      status: "upcoming",
      due_at: daysFromNow(45),
    },
    {
      id: "t4",
      label: "Student Services & Health Insurance Fee",
      term: "Spring 2026",
      amount_vnd: 80_000_000,
      status: "paid",
      paid_at: daysFromNow(-40),
    },
  ],
};

export const MOCK_TICKETS: SupportTicket[] = [
  {
    id: "TKT-2041",
    subject: "Scholarship renewal criteria for Year 3",
    body: "I couldn't find a verified answer on whether my merit scholarship auto-renews if my GPA stays above 3.5.",
    department: "Office of Financial Aid",
    category: "academic",
    status: "in_review",
    priority: "high",
    confirmed_by_user: true,
    created_by_ai: true,
    include_chat_context: false,
    submitted_at: daysFromNow(-2, 10, 12),
    created_at: daysFromNow(-2, 10, 12),
    updated_at: daysFromNow(-1, 16, 30),
    student_name: "Nguyễn Minh Anh",
    assignee: "Financial Aid Staff",
    due_at: daysFromNow(-3, 17, 0), // past → overdue (anchored to NOW=2026-06-18)
    origin_question: "Does my merit scholarship renew automatically for Year 3?",
    messages: [
      {
        id: "m1",
        author: "student",
        body: "Does my merit scholarship renew automatically for Year 3 if my GPA stays above 3.5?",
        created_at: daysFromNow(-2, 10, 12),
      },
      {
        id: "m2",
        author: "admin",
        body: "Thanks for reaching out — the Office of Financial Aid is reviewing your scholarship terms and will reply within 2 business days.",
        created_at: daysFromNow(-1, 16, 30),
      },
    ],
  },
  {
    id: "TKT-2038",
    subject: "Exchange semester credit transfer",
    body: "Question forwarded from the assistant: how do credits from a partner university map back to my degree audit?",
    department: "Office of the Registrar",
    category: "academic",
    status: "resolved",
    priority: "medium",
    confirmed_by_user: true,
    created_by_ai: true,
    include_chat_context: false,
    submitted_at: daysFromNow(-9, 9, 5),
    created_at: daysFromNow(-9, 9, 5),
    updated_at: daysFromNow(-5, 11, 20),
    student_name: "Nguyễn Minh Anh",
    assignee: "Registrar Staff",
    origin_question: "How do exchange-semester credits transfer back to my CS degree?",
    resolution:
      "Credits transfer as electives once the Registrar receives the partner transcript; pre-approval via the Study Abroad form is required.",
    source_title: "Undergraduate Student Handbook 2025 — Credit Transfer",
    source_url: "https://vinuni.edu.vn/handbook-2025.pdf",
    messages: [
      {
        id: "m1",
        author: "student",
        body: "How do exchange-semester credits transfer back to my CS degree?",
        created_at: daysFromNow(-9, 9, 5),
      },
      {
        id: "m2",
        author: "admin",
        body: "Credits transfer as electives once the Registrar receives the partner transcript; pre-approval via the Study Abroad form is required.",
        created_at: daysFromNow(-5, 11, 20),
      },
    ],
  },
  {
    id: "TKT-2033",
    subject: "Lab booking system shows an error on checkout",
    body: "When I try to book a slot in the Gallery Building lab, the portal returns a 500 error after I pick a time.",
    department: "IT Help Desk",
    category: "technical",
    status: "waiting_for_student",
    priority: "medium",
    confirmed_by_user: true,
    created_by_ai: false,
    include_chat_context: false,
    submitted_at: daysFromNow(-3, 8, 40),
    created_at: daysFromNow(-3, 8, 40),
    updated_at: daysFromNow(-1, 9, 15),
    student_name: "Trần Gia Bảo",
    assignee: "IT Help Desk",
    due_at: daysFromNow(0, 20, 0), // within ~24h of NOW → due_soon
  },
  {
    id: "TKT-2025",
    subject: "Locker assignment for Gallery Building",
    body: "Requesting a locker near the CS labs for the Spring term.",
    department: "Student Affairs",
    category: "student_services",
    status: "closed",
    priority: "low",
    confirmed_by_user: true,
    created_by_ai: false,
    include_chat_context: false,
    submitted_at: daysFromNow(-21, 14, 0),
    created_at: daysFromNow(-21, 14, 0),
    updated_at: daysFromNow(-18, 15, 0),
    student_name: "Lê Thu Hà",
    assignee: "Student Affairs",
    resolution: "Locker G2-117 assigned for Spring 2026.",
  },
  {
    id: "TKT-2011",
    subject: "Old request about library opening hours",
    body: "Asked about weekend library hours last term — no longer needed.",
    department: "Student Affairs",
    category: "other",
    status: "closed",
    priority: "low",
    confirmed_by_user: true,
    created_by_ai: false,
    include_chat_context: false,
    submitted_at: daysFromNow(-60, 11, 0),
    created_at: daysFromNow(-60, 11, 0),
    updated_at: daysFromNow(-58, 12, 0),
    student_name: "Phạm Quốc Huy",
    assignee: "Student Affairs",
    archived: true,
    resolution: "Weekend hours: 9:00–18:00 (Sat–Sun).",
  },
];

// [MOCK] TODO backend contract: GET /students/me/notifications -> Notification[]
export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n-1",
    type: "deadline",
    title: "Course Drop deadline approaching",
    message:
      "The deadline to drop a course without a W on your transcript is approaching. Confirm your schedule before it closes.",
    created_at: daysFromNow(0, 8, 5),
    read: false,
    important: true,
    priority: "high",
    status: "published",
    deadline: daysFromNow(6),
    source_title: "Academic Calendar 2025–2026",
    source_url: "https://vinuni.edu.vn/academic-calendar",
    action_label: "View deadline",
    action_href: "/student/schedule",
    suggested_questions: [
      {
        id: "sq-n1-1",
        notification_id: "n-1",
        question_text: "How do I drop a course before the deadline?",
        category: "deadline",
        trigger_phase: "near_deadline",
        score: 0.95,
        created_by_ai: true,
        approved_by_admin: true,
        is_active: true,
        created_at: daysFromNow(0, 8, 5),
        updated_at: daysFromNow(0, 8, 5),
      },
      {
        id: "sq-n1-2",
        notification_id: "n-1",
        question_text: "Will dropping a course put a W on my transcript?",
        category: "deadline",
        trigger_phase: "near_deadline",
        score: 0.8,
        created_by_ai: true,
        approved_by_admin: true,
        is_active: true,
        created_at: daysFromNow(0, 8, 5),
        updated_at: daysFromNow(0, 8, 5),
      },
      {
        id: "sq-n1-3",
        notification_id: "n-1",
        question_text: "Who do I contact if I miss the course drop deadline?",
        category: "deadline",
        trigger_phase: "overdue",
        score: 0.7,
        created_by_ai: true,
        approved_by_admin: true,
        is_active: true,
        created_at: daysFromNow(0, 8, 5),
        updated_at: daysFromNow(0, 8, 5),
      },
    ],
  },
  {
    id: "n-2",
    type: "schedule",
    title: "Room change for Database Systems",
    message: "COMP3025 on Thursday has moved from G-114 to G-118 for this week only.",
    created_at: daysFromNow(0, 7, 30),
    read: false,
    important: false,
    action_label: "Open calendar",
    action_href: "/student/schedule",
  },
  {
    id: "n-3",
    type: "academic",
    title: "Midterm grades are being released",
    message: "Some of your midterm grades are now visible in the student portal.",
    created_at: daysFromNow(-1, 15, 10),
    read: false,
    important: false,
  },
  {
    id: "n-4",
    type: "event",
    title: "CS Career Fair — Friday",
    message:
      "Meet 20+ tech companies at the Gallery Building atrium, 13:00–17:00. Bring your CV.",
    created_at: daysFromNow(-1, 9, 0),
    read: true,
    important: false,
    priority: "medium",
    status: "published",
    event_date: daysFromNow(3, 13, 0),
    action_label: "See event",
    action_href: "/student/schedule",
    suggested_questions: [
      {
        id: "sq-n4-1",
        notification_id: "n-4",
        question_text: "What companies are attending the CS Career Fair?",
        category: "event",
        trigger_phase: "active",
        score: 0.85,
        created_by_ai: true,
        approved_by_admin: true,
        is_active: true,
        created_at: daysFromNow(-1, 9, 0),
        updated_at: daysFromNow(-1, 9, 0),
      },
      {
        id: "sq-n4-2",
        notification_id: "n-4",
        question_text: "Do I need to register for the CS Career Fair?",
        category: "event",
        trigger_phase: "active",
        score: 0.75,
        created_by_ai: true,
        approved_by_admin: true,
        is_active: true,
        created_at: daysFromNow(-1, 9, 0),
        updated_at: daysFromNow(-1, 9, 0),
      },
    ],
  },
  {
    id: "n-5",
    type: "student_services",
    title: "Health insurance card ready for pickup",
    message: "Your Spring 2026 health insurance card is available at the Student Services desk.",
    created_at: daysFromNow(-2, 11, 20),
    read: true,
    important: false,
  },
  {
    id: "n-6",
    type: "system",
    title: "Scheduled maintenance Saturday 02:00",
    message: "The student portal will be briefly unavailable during a maintenance window.",
    created_at: daysFromNow(-3, 18, 0),
    read: true,
    important: false,
  },
];

// [MOCK] Standalone campus events + personal reminders merged into the calendar feed
// alongside classes (MOCK_SCHEDULE) and deadlines (MOCK_DEADLINES). See getStudentCalendar.
export const MOCK_EVENTS: CalendarEvent[] = [
  {
    id: "ev-1",
    type: "event",
    title: "CS Career Fair",
    start: daysFromNow(3, 13, 0),
    end: daysFromNow(3, 17, 0),
    location: "Gallery Building Atrium",
    category: "Career",
    description: "Meet 20+ tech companies. Bring printed copies of your CV.",
    source_title: "Student Events Calendar (Spring 2026)",
    source_url: "https://vinuni.edu.vn/events",
  },
  {
    id: "ev-2",
    type: "event",
    title: "Guest Lecture: Applied Machine Learning",
    start: daysFromNow(5, 16, 0),
    end: daysFromNow(5, 17, 30),
    location: "C-201, Cohort Building",
    category: "Academic",
    description: "Industry talk on ML systems in production. Open to all CS students.",
    source_title: "Student Events Calendar (Spring 2026)",
    source_url: "https://vinuni.edu.vn/events",
  },
  {
    id: "ev-3",
    type: "event",
    title: "Lunar New Year Celebration",
    start: daysFromNow(8, 18, 0),
    end: daysFromNow(8, 21, 0),
    location: "Main Campus Plaza",
    category: "Community",
    description: "Food stalls, performances, and student club showcases.",
  },
];

export const MOCK_REMINDERS: CalendarEvent[] = [
  {
    id: "rm-1",
    type: "reminder",
    title: "Pay tuition installment 2",
    start: daysFromNow(11, 9, 0),
    all_day: true,
    category: "Personal",
    description: "Set from your tuition status — pay before the due date to avoid a late fee.",
  },
  {
    id: "rm-2",
    type: "reminder",
    title: "Book advising appointment",
    start: daysFromNow(2, 10, 0),
    all_day: true,
    category: "Personal",
    description: "Meet your advisor before course registration opens.",
  },
];

export const MOCK_SOURCES: KnowledgeSource[] = [
  {
    id: "src-1",
    name: "Academic Calendar 2025–2026",
    url: "https://vinuni.edu.vn/academic-calendar",
    type: "url",
    category: "Academic",
    status: "indexed",
    chunk_count: 42,
    last_crawled_at: daysFromNow(-1, 3, 0),
    last_indexed_at: daysFromNow(-1, 3, 12),
    is_official: true,
  },
  {
    id: "src-2",
    name: "Undergraduate Student Handbook 2025",
    url: "https://vinuni.edu.vn/handbook-2025.pdf",
    type: "pdf",
    category: "Academic",
    status: "indexed",
    chunk_count: 318,
    last_crawled_at: daysFromNow(-3, 2, 0),
    last_indexed_at: daysFromNow(-3, 2, 40),
    is_official: true,
  },
  {
    id: "src-3",
    name: "Tuition & Payment Schedule",
    url: "https://vinuni.edu.vn/tuition-payment-schedule",
    type: "url",
    category: "Tuition",
    status: "indexed",
    chunk_count: 27,
    last_crawled_at: daysFromNow(0, 3, 0),
    last_indexed_at: daysFromNow(0, 3, 8),
    is_official: true,
  },
  {
    id: "src-4",
    name: "Course Withdrawal & Leave of Absence Policy",
    url: "https://vinuni.edu.vn/policies/withdrawal.pdf",
    type: "pdf",
    category: "Academic",
    status: "indexed",
    chunk_count: 16,
    last_crawled_at: daysFromNow(-2, 4, 0),
    last_indexed_at: daysFromNow(-2, 4, 18),
    is_official: true,
  },
  {
    id: "src-5",
    name: "Student Events Calendar (Spring 2026)",
    url: "https://vinuni.edu.vn/events",
    type: "url",
    category: "Events",
    status: "crawling",
    chunk_count: 0,
    last_crawled_at: daysFromNow(0, 3, 0),
    is_official: true,
  },
  {
    id: "src-6",
    name: "Health & Counseling Services",
    url: "https://vinuni.edu.vn/student-services/health",
    type: "url",
    category: "Student Services",
    status: "failed",
    chunk_count: 0,
    last_crawled_at: daysFromNow(0, 2, 30),
    is_official: true,
  },
  {
    id: "src-7",
    name: "Legacy FAQ export (2023)",
    url: "https://drive.vinuni.edu.vn/legacy-faq",
    type: "database",
    category: "Student Services",
    status: "disabled",
    chunk_count: 88,
    last_crawled_at: daysFromNow(-120, 1, 0),
    last_indexed_at: daysFromNow(-120, 1, 30),
    is_official: false,
  },
];

export const MOCK_UNANSWERED: UnansweredQuestion[] = [
  {
    id: "q-501",
    question: "Can I defer my tuition installment if my scholarship disbursement is late?",
    reason: "no_verified_source",
    student_context: "Year 2 · CECS · merit scholarship holder",
    suggested_department: "Student Financial Services",
    priority: "high",
    status: "new",
    created_at: daysFromNow(0, 7, 40),
    asked_count: 6,
  },
  {
    id: "q-502",
    question: "What is the exact GPA cutoff for the Dean's List this semester?",
    reason: "low_confidence",
    student_context: "Year 3 · College of Business",
    suggested_department: "Office of the Registrar",
    priority: "medium",
    status: "new",
    created_at: daysFromNow(-1, 13, 12),
    asked_count: 3,
  },
  {
    id: "q-503",
    question: "Is there a shuttle bus schedule between the dorms and the main campus on weekends?",
    reason: "no_verified_source",
    student_context: "Year 1 · resident student",
    suggested_department: "Student Affairs",
    priority: "medium",
    status: "in_review",
    created_at: daysFromNow(-2, 9, 0),
    asked_count: 11,
  },
  {
    id: "q-504",
    question: "How do I appeal a final grade in a core engineering course?",
    reason: "ambiguous",
    student_context: "Year 2 · CECS",
    suggested_department: "Office of the Registrar",
    priority: "low",
    status: "forwarded",
    created_at: daysFromNow(-4, 10, 30),
    asked_count: 2,
  },
];

export const MOCK_ADMIN_STATS: AdminStats = {
  indexed_documents: 1284,
  sources_crawled_today: 9,
  failed_crawls: 1,
  unanswered_questions: 4,
  verified_answer_rate: 0.91,
  low_confidence_responses: 12,
};

export const MOCK_ANALYTICS: AnalyticsOverview = {
  questions_per_day: [
    { label: "Mon", total: 142, verified: 129, unanswered: 5 },
    { label: "Tue", total: 168, verified: 151, unanswered: 7 },
    { label: "Wed", total: 155, verified: 142, unanswered: 4 },
    { label: "Thu", total: 191, verified: 173, unanswered: 9 },
    { label: "Fri", total: 176, verified: 160, unanswered: 6 },
    { label: "Sat", total: 88, verified: 80, unanswered: 3 },
    { label: "Sun", total: 71, verified: 65, unanswered: 2 },
  ],
  top_topics: [
    { topic: "Tuition & payments", count: 248 },
    { topic: "Deadlines & calendar", count: 213 },
    { topic: "Course registration", count: 187 },
    { topic: "Student services", count: 121 },
    { topic: "Events", count: 76 },
  ],
  avg_confidence: 0.83,
  verified_rate: 0.91,
  total_questions: 991,
};

// Small helper so api.ts can simulate network latency uniformly for the mock path.
export function delay<T>(value: T, ms = 280): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), ms));
}
